- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies no longer needed"
  become: yes
  apt:
    autoremove: yes

- name: "install nodejs abd npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install PM2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    version: 3.5.2
  
- name: create web directory
  file: 
    path: ~/web
    state: directory

- name: copy file to server
  become: yes
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: start web server
  become: yes
  shell: pm2 start ~/web/index.js -f
